services:
  bot:
    build: .
    env_file: stack.env
    volumes:
      - /home/simo/docker/reservation-bot/data:/app/data
      - /home/simo/docker/reservation-bot/logs:/app/.logs
    restart: unless-stopped
